### ISSUE TITLE
Unkillable Uniques

### ISSUE THREAD

**Issue by Pollogrande** [Dynarev/mythmoor#3]

**Comment by Pollogrande** [comment]
Uniques are still having unkillablity issues. May be caused by being above cave tiles in the Crawl.

**Comment by Dynarev** [comment]
Uniques need to be summoned in a more careful place. We had already went over that caves would be the only reason something was strange, and furthermore it seems the cave in questions both times is a protected cave. Protected tiles may be the issue. Don't summon uniques in these areas.
